### ISSUE TITLE
wireshark plugin doesn't use 000000000000 for empty JA4_c

### ISSUE THREAD

**Issue by awick** [FoxIO-LLC/ja4#164]
If I have a empty JA4_c, wireshark plugin hashes as e3b0c44298fc while Arkime and the ja4/rust use 000000000000, which is correct?

**Comment by john-althouse** [comment]
It should be zeros. That's a bug, thanks for bringing it up!

**Comment by john-althouse** [comment]
@awick can you send me a pcap?

We stopped supporting JA4 for Wireshark in our plugin because it's already included in the base version of Wireshark - no need to have it in there twice. So our plugin now only includes JA4+ (all of the other fingerprints) - similar to Arkime. That means this bug for JA4 in Wireshark will need to be fixed by the Wireshark team.

**Comment by awick** [comment]
4.4.0 is showing t10d190100_7b6e7846fca7_e3b0c44298fc rust/arkime t10d190100_7b6e7846fca7_000000000000

[ja4_c-should-be-0s.pcap.gz](https://github.com/user-attachments/files/16969766/ja4_c-should-be-0s.pcap.gz)

**Comment by john-althouse** [comment]
I updated the JA4 spec to make this clear and created an issue here: https://gitlab.com/wireshark/wireshark/-/issues/20066

**Comment by john-althouse** [comment]
Fixed: https://gitlab.com/wireshark/wireshark/-/merge_requests/17679
